class ResponseConstants
  STORED = "STORED"
  NOT_STORED = "NOT_STORED"
  EXISTS = "EXISTS"
  NOT_FOUND = "NOT_FOUND"
  ERROR = "ERROR"
  CLIENT_ERROR = "CLIENT_ERROR"
  SERVER_ERROR = "SERVER_ERROR"
  LINE_FORMAT_ERROR = "bad command line format"
  BAD_DATA_ERROR = "bad data chunk"
  SELECT_IP_DIRECTION = "Select an IP direction:"
  SELECT_PORT = "Select a port:"
  SERVER_CONNECTED_TEMPLATE = "Server started in: %s:%d"
  CLIENT_CONNECTED_TEMPLATE = "New connection from: %s:%d"
  CLIENT_DISCONNECTED_TEMPLATE = "Client %s:%d disconnected"
  ITEM_TEMPLATE = "VALUE %s %d %d"
  ITEM_CAS_TEMPLATE = "VALUE %s %d %d %d"
  VALUE_TEMPLATE = "%s"
  ERROR_TEMPLATE = "%s %s"
  END_ = "END"
  ERROR_REGEX = /ERROR/
end
